blank_issues_enabled: true
contact_links:
  - name: No Github account? Don't know how to use Github?
    url: https://docs.qq.com/form/page/DSlFOZmpTQ1JsZ2FD
    about: Click here to use Tencent Docs to fill out Bug reports
